### ISSUE TITLE
Error with flickr API: Photoset not found

### ISSUE THREAD

**Issue by snarfed** [lmammino/flickr-set-get#19]
hi! thanks for writing flickr-set-get! i'm getting this error when i try to download a private photo set that i have a guest pass for. is that not supported?

```
$ flickr-set-get 72157653461216005 49022499@N00
ERROR: Error: Error with flickr API: Photoset not found (https://api.flickr.com/services/rest?photoset_id=72157653461216005&user_id=49022499%40N00&page=1&nojsoncallback=1&format=json&api_key=80ff7d163768e25928db697db1783e35&method=flickr.photosets.getPhotos)
```

**Comment by lmammino** [comment]
Hey @snarfed, glad someone found `flickr-set-get` useful.
Unfortunately I haven't tested this case and I don't expect it to be supported. 
It probably requires to use some kind of authentication mechanism or to send some password along with the API request.
I will open a specific issue with this case and I will try to get into the details as soon as I have some free time.

Sorry for the inconvenience.

**Comment by lmammino** [comment]
Hey @snarfed, I started to work on this issue some days ago, see [dedicated branch](https://github.com/lmammino/flickr-set-get/tree/authentication) and opened a dedicated issue: #20 .

I'll update you once it's finished and published on NPM (I hope before the end of this week).

Regards

**Comment by snarfed** [comment]
that's great news, thank you!

**Comment by lmammino** [comment]
@snarfed just published (with a small delay 😅) the new version (1.1.0) that supports authenticated requests.
Please let me know if it works for you!

**Comment by snarfed** [comment]
thanks so much for implementing this @lmammino!

**Comment by lmammino** [comment]
You are very welcome @snarfed
