### ISSUE TITLE
ERROR: Error: Error with flickr API: Photoset not found

### ISSUE THREAD

**Issue by thehaven** [lmammino/flickr-set-get#28]
I get the above error when trying to download an AutoUpload album (the only album I have). Not sure if this has anything to do with the change in URI from Set to Album in the API or whether its a special condition on the AutoUpload album.

Any help appreciated. Thanks.

**Comment by lmammino** [comment]
Hello @thehaven ,
thanks for having reported this issue.

Are you currently using authentication as explained in the [documentation](https://github.com/lmammino/flickr-set-get#download-private-photos-and-sets)?

If yes can you please describe all the steps that I should do to recreate the issue.

Thanks again!

**Comment by thehaven** [comment]
Hi @lmammino,

Thanks for getting back to me. Yes I've walked through those steps as part of the setup. The only difference is that my URL used is of the format:

https://www.flickr.com/photos/<userID>/albums/<set ID>
Rather than the documented example:
https://www.flickr.com/photos/<userID>/sets/<set ID>.

Let me know what details would help or whether the above is the problem and I'll provide as required.

Regards

**Comment by lmammino** [comment]
Thanks Simon @thehaven for the very detailed reply.

I recreated a case like yours (where I have an "albums" url) with private photos inside and after having setup my credentials it seems to be working.

On your instructions I noticed you are not using the `--authenticated` flag. When you don't use this flag the command will not issue a request signed with your credentials so flickr will get an anonymous request and if your album does not contain any public photo it will tell you that the photoset is not found. I should probably make the error message more descriptive and explain this possibility when a "Photoset not found" occurs.

Can you please try again using the `--authenticated` flag? 

E.g.

```bash
flickr-set-get get --authenticated <setID> <userID>
```

Hope this works for you.
Thank you in advance!

**Comment by lmammino** [comment]
On a side note I just realized that Flickr finally implemented a download feature on the albums! 😈

![Flickr Download albums feature screenshot](https://cloud.githubusercontent.com/assets/205629/10178262/8ffe111c-66f6-11e5-954b-a265f3181463.png)

**Comment by thehaven** [comment]
Thank you Luciano @lmammino,

It was the fact I was missing --authenticated in my request, adding that made it work perfectly. Many thanks for all your help :)

I'll close this off now as user error.

Regards

Simon

**Comment by lmammino** [comment]
You are very welcome! I am glad that it is working for you now.

Best regards
