### ISSUE TITLE
Limited number of photos in larger set found

### ISSUE THREAD

**Issue by tanc** [lmammino/flickr-set-get#29]
When trying to run a `flickr-set-get get` its only seeing 443 photos in the set, rather than the full 10,127 photos that are actually there. Any ideas where to start debugging?

```INFO: Downloading 443 photos from...```

**Comment by lmammino** [comment]
Are you making authenticated requests? Do you have private photos on the set?

**Comment by tanc** [comment]
I'm making authenticated requests. I probably have private photos

**Comment by lmammino** [comment]
If you are making authenticated requests you should be able to download also all the private photos in the set (of course, if and only if the user you are authenticated with have access to these photos). Can you please check on Flickr what is the current status of privacy of the photos in the set?

**Comment by tanc** [comment]
Ah, I realised I was missing the `--authenticated` switch and had assumed the call was authenticated after going through the set up. I'll close this now, thanks for your help!

**Comment by lmammino** [comment]
Glad to know you sorted it out (and most importantly that it wasn't a bug :relieved:).
Thanks for using this code anyway, feel free to provide feedbacks or ideas for improvement.
